apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adp-portal
  annotations:
    github.com/project-slug: defra-adp-sandpit/adp-portal
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: FCP Grants
